---
title: "2018 Fall Final Projects of Gov 1005 Review"
author: "Hemanth Bharatha Chakravarthy"
date: "4/1/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Project 1: Deaths over the course of the Syrian Civil War

Project title: Analysis of the deaths over the course of the Syrian Civil War

Author: Cayanne Chachati

Link: https://cayanne.shinyapps.io/syrian_civil_war/


### Pros

- Filters and subsetting: in both the main analyses tabs, you can filter for parameters like cause of death, gender, adulthood status, etc. and observe the group you wish to or choose your own subset provinces
- There's also proper guidance on how to use interactive plots


### Cons

- Error not fixed: in filtered deaths, if you seek to filter by affiliation, Shiny throws an error: `Error: An error has occurred. Check your logs or contact the app author for clarification.`
- The plots don't gain much from being interactive other than the ability to zoom in on them
- The plot on the home tab makes no sense to me: it's a dotplot with time on x axis and things like "international politics" on the Y axis--what does it mean for a year to have dot? Presumably these political events happened with more complex timelines that just one dot a year?
- Second and third tabs are identical: you have to option to filter by province and look at the line plot or go to another tab and look at the barplot. 
        - I guess the bar plot lets you choose fewer provinces but maybe instead of having a drop-down menu, each parameter could have been a tab with further exploration of the data?
        
        
        
# Project 2: Indian Exports

Project title: Analysis of Indian exports between 2014 and 2017.

Author: Rana Chandra Bansal

Link: https://ranban.shinyapps.io/Shiny/


### Pros

- Analyzing data accross multiple parameters: the various tabs cleanly sort out how Indian exports varied accross different lenses of analyses like top partners, top commodities, and some specific products
- Use of interactive visualization: in the various tabs, you are able to search accross specific years and goods to find specific information you need, so that's useful
- The UI/UX of the page is very cool; very intuitive and aesthetic design


### Cons

- Choice of visualization: Though interactive, none of the visualizations are otherwise too attractive and interesting--bar plots and tables don't perhaps best convey the information to users
- Scale of graphs/illegible scatter plot: in both the scatterplots of iron and steel and coffee, there are too many points clustered together to be able to distinguish; there could have been fewer countries chosen and a log y scale used
- Geospatial analysis would have been cool here: the home tab has a map but it just seems like an empty world map attached through an API
- Choice of link just being a shinyapp.com/Shiny is a bad design choice for naming the link

